FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as buils-env
WORKDIR /app

#copy csproj and restore as distinct layer
COPY *.csproj ./

#restote packages
RUN dotnet restore

#copy everything else and build
COPY . ./

#build Order Service
RUN dotnet publish -c Release -o out

# build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 as runtime
WORKDIR /app
#publised files of Orderservice present in /App/OrderService/out filder
COPY --from=buils-env /app/out ./
ENTRYPOINT ["dotnet","TeaService.dll"]